events {
  worker_connections 1024;
}

http {
  upstream frontend_upstream {
    server frontend:80;
  }

  upstream load_balancer_upstream {
    server load-balancer:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://frontend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ {
      proxy_pass http://load_balancer_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health {
      return 200 'ok';
      add_header Content-Type text/plain;
    }
  }
}