server.port=8080

spring.datasource.url=jdbc:postgresql://database:5432/taskflow
spring.datasource.username=taskflow
spring.datasource.password=geheim123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

notification.service.url=http://notification-service:5000